FORMAT: 1A
HOST: http://spacecowboys.me/

# Space Cowboys

Space Cowboys is an API allowing users to get information about various celestial objects.
For all of these objects, you can retrieve the full collection of each or retrieve an indivpidual object by pid or name.

# Group Satellites

## Satellite by ID [/satellites/{pid}]

+ Parameters
    + pid (number) - pID of the Satellite in the form of an integer


### Retrieve a Satellite by ID [GET]

+ Response 200 (application/json)

    + Attributes (object)
        + pid: 2(number, required)
        + name: Nuclear Spectroscopic Telescope Array NuSTAR (string)
        + year launched: 2012(number)
        + mission type: astrophysics(string)
        + agency: National Aeronautics and Space Administration(string)


    + Headers

            Location: /satellites/2

    + Body

            {
                "pid": 2,
                "name": "Nuclear Spectroscopic Telescope Array (NuSTAR)",
                "year launched": 2012,
                "mission type": "astrophysics",
                "agency": "National Aeronautics and Space Administration"
            }     
    
+ Response 204 (application/json)  

## Satellite by Name [/satellites/{name}]

+ Parameters
    + name (string) - name of the Satellite in the form of a string


### Retrieve a Satelllite by Name [GET]

+ Response 200 (application/json)

    + Attributes (object)
        + pid: 2(number)
        + name: Nuclear Spectroscopic Telescope Array NuSTAR (string, required)
        + year launched: 2012(number)
        + mission type: astrophysics(string)
        + agency: National Aeronautics and Space Administration(string)

    + Headers

            Location: /satellites/2

    + Body

            {
                "pid": 2,
                "name": "Nuclear Spectroscopic Telescope Array (NuSTAR)",
                "year launched": 2012,
                "mission type": "astrophysics",
                "agency": "National Aeronautics and Space Administration"
            }       

+ Response 204 (application/json)

## Satellites by Year [/satellites{year}]

### Retrieve Satellites by Year [GET]

+ Parameters

    + year (number, optional) - Returns all satellites launched in the given year.

+ Response 200 (application/json)

        [
            {
                "pid": 1,
                "name":"WGS-4 (USA-233)",
                "year launched": 2012,
                "mission type": "communications",
                "agency": "United Launch Alliance"
            },
            {
                "pid": 2,
                "name": "Nuclear Spectroscopic Telescope Array (NuSTAR)",
                "year launched": 2012,
                "mission type": "astrophysics",
                "agency": "National Aeronautics and Space Administration"
            }
        ]
        
+ Response 204 (application/json)

## Satellites Collection [/satellites{?limit}]

### Retrieve All Satellites [GET]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `10`

+ Response 200 (application/json)

        [
            {
                "pid": 1,
                "name":"WGS-4 (USA-233)",
                "year launched": 2012,
                "mission type": "communications",
                "agency": "United Launch Alliance"
            },
            {
                "pid": 2,
                "name": "Nuclear Spectroscopic Telescope Array (NuSTAR)",
                "year launched": 2012,
                "mission type": "astrophysics",
                "agency": "National Aeronautics and Space Administration"
            }
        ]
        
+ Response 204 (application/json)        
        
# Group Planetopid Bodies

## Planetopid Body by ID [/planetoids/pid]

### Retrieve a Single Planet by ID [GET]

+ Request (application/json)

        {
            "pid":2
        }

+ Response 200 (application/json)

    + Attributes (object)
        + pid: 2(number, required)
        + name: HAT P 34 b (string)
        + dec: 18.104868 (number)
        + ra: 303.195342 (number)
        + picture: HAT P 34 b.png (string)
        + host: HAT P 34 (string)
        + gravity: 0.06019932261381838 (number)
        + orbital_period: 5.452654 (number)
        + name: HAT-P-34 b (string)
        + diamter: 167366.934 (number)
        + temperature: 1520 (number)
        + mass: 6.316544e+27 (number)
        + host_pid: 1 (number)
        + star_pid: 1 (number)
        + galaxy_pid: 1 (number)

    + Headers

            Location: /planets/2

    + Body

            {
                "pid": 2
                "dec": 18.104868,
                "ra": 303.195342,
                "picture": "HAT-P-34 b.png",
                "host": "HAT-P-34",
                "gravity": 0.06019932261381838,
                "orbital_period": 5.452654,
                "name": "HAT-P-34 b",
                "diamter": 167366.934,
                "temperature": 1520,
                "mass": 6.316544e+27,
                "host_pid": 1,
                "star_pid": 1,
                "galaxy_pid": 1
            }

+ Response 204 (application/json)

## Planetopid Body by Name [/planetoids/name]

### Retrieve a Single Planet by Name [GET]

+ Request (application/json)

        {
            "name": "HAT-P-34 b"
        }

+ Response 200 (application/json)

    + Attributes (object)
        + pid: 2(number)
        + name: HAT P 34 b (string, required)
        + dec: 18.104868 (number)
        + ra: 303.195342 (number)
        + picture: HAT P 34 b.png (string)
        + host: HAT P 34 (string)
        + gravity: 0.06019932261381838 (number)
        + orbital_period: 5.452654 (number)
        + name: HAT-P-34 b (string)
        + diamter: 167366.934 (number)
        + temperature: 1520 (number)
        + mass: 6.316544e+27 (number)
        + host_pid: 1 (number)
        + star_pid: 1 (number)
        + galaxy_pid: 1 (number)

    + Headers

            Location: /planets/2

    + Body

            {
                "pid": 2
                "dec": 18.104868,
                "ra": 303.195342,
                "picture": "HAT-P-34 b.png",
                "host": "HAT-P-34",
                "gravity": 0.06019932261381838,
                "orbital_period": 5.452654,
                "name": "HAT-P-34 b",
                "diamter": 167366.934,
                "temperature": 1520,
                "mass": 6.316544e+27,
                "host_pid": 1,
                "star_pid": 1,
                "galaxy_pid": 1
            }

+ Response 204 (application/json)


## Planetopid Bodies Collection [/planetopids{?limit}]

### Retrieve All Planets [GET]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `10`

+ Response 200 (application/json)

        [
            {
                "pid": 1,
                "dec": 33.835052,
                "ra": 113.184212,
                "picture": "HAT-P-33 b.png",
                "host": "HAT-P-33",
                "gravity": 0.006947625786270114,
                "orbital_period": 3.474474,
                "name": "HAT-P-33 b",
                "diamter": 235739.892,
                "temperature": 1782,
                "mass": 1.446276e+27,
                "host_pid": null,
                "star_pid": 1,
                "galaxy_pid": 1
            },
            {
                "pid": 2
                "dec": 18.104868,
                "ra": 303.195342,
                "picture": "HAT-P-34 b.png",
                "host": "HAT-P-34",
                "gravity": 0.06019932261381838,
                "orbital_period": 5.452654,
                "name": "HAT-P-34 b",
                "diamter": 167366.934,
                "temperature": 1520,
                "mass": 6.316544e+27,
                "host_pid": 1,
                "star_pid": 1,
                "galaxy_pid": 1
            }
        ]

+ Response 204 (application/json)

# Group Stars

## Star by ID [/stars/pid]

### Retrieve a Single Star by ID [GET]

+ Request (application/json)

        {
            "pid": 2
        }

+ Response 200 (application/json)

    + Attributes (object)
        + pid: 2(number, required)
        + name: HAT P 33 (string)
        + dec: 33.835052 (number)
        + ra: 113.184212 (number)
        + picture: HAT P 33.png (string)
        + temperature: 6446.0 (number)
        + mass: 1.38 (number)
        + distance: 0 (number)
        + galaxy_pid: 1 (number)

    + Headers

            Location: /stars/2

    + Body

            {
                "pid": 2,
                "dec": 33.835052,
                "ra": 113.184212,
                "picture": "HAT-P-33.png",
                "name": "HAT-P-33",
                "distance": null,
                "temperature": 6446.0,
                "mass": 1.38,
                "galaxy_pid": 1
            }

+ Response 204 (application/json)

## Star by Name [/stars/name]

### Retrieve a Single Star by Name [GET]

+ Request (application/json)

        {
            "name": "HAT-P-33"
        }

+ Response 200 (application/json)

    + Attributes (object)
        + pid: 2(number)
        + name: HAT P 33 (string, required)
        + dec: 33.835052 (number)
        + ra: 113.184212 (number)
        + picture: HAT P 33.png (string)
        + temperature: 6446.0 (number)
        + mass: 1.38 (number)
        + distance: 0 (number)
        + galaxy_pid: 1 (number)

    + Headers

            Location: /stars/2

    + Body

            {
                "pid": 2,
                "dec": 33.835052,
                "ra": 113.184212,
                "picture": "HAT-P-33.png",
                "name": "HAT-P-33",
                "distance": null,
                "temperature": 6446.0,
                "mass": 1.38,
                "galaxy_pid": 1
            }

+ Response 204 (application/json)

## Stars Collection [/stars{?limit}]

### Retrieve All Stars [GET]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `10`

+ Response 200 (application/json)

        [
            {
                "pid": 1,
                "dec": 48.040234,
                "ra": 288.793037,
                "picture": "Kepler-117.png",
                "name": "Kepler-117",
                "distance": null,
                "temperature": 6150.0,
                "mass": 1.13,
                "galaxy_pid": 1
            },
            {
                "pid": 2,
                "dec": 33.835052,
                "ra": 113.184212,
                "picture": "HAT-P-33.png",
                "name": "HAT-P-33",
                "distance": null,
                "temperature": 6446.0,
                "mass": 1.38,
                "galaxy_pid": 1
            }
        ]

+ Response 204 (application/json)


# Group Galaxies

## Galaxy by ID [/galaxies/pid]

### Retrieve a Single Galaxy by ID [GET]

+ Request (application/json)

        {
            "pid": 2
        }

+ Response 200 (application/json)

    + Attributes (object)
        + pid: 2(number, required)
        + name: UGC 11822 (string)
        + dec: 40.663325 (number)
        + ra: 327.418700 (number)
        + picture: UGC 11822.png (string)
        + type: barred spiral (string)
        + redshift: 0.014739 (number)
        + size: 1.170 (number)

    + Headers

            Location: /galaxies/2

    + Body

            {
                "pid": 2,
                "name": "UGC 11822",
                "image": "UGC 11822.png",
                "ra": 327.418700,
                "dec": 40.663325,
                "type": "barred spiral",
                "redshift": 0.014739,
                "size": 1.170
            }
            
+ Response 204 (application/json)

## Galaxy by Name [/galaxies/name]

### Retrieve a Single Galaxy by Name [GET]

+ Request (application/json)

        {
            "name": "UGC 11822"
        }

+ Response 200 (application/json)

    + Attributes (object)
        + pid: 2(number)
        + name: UGC 11822 (string, required)
        + dec: 40.663325 (number)
        + ra: 327.418700 (number)
        + picture: UGC 11822.png (string)
        + type: barred spiral (string)
        + redshift: 0.014739 (number)
        + size: 1.170 (number)

    + Headers

            Location: /galaxies/2

    + Body

            {
                "pid": 2,
                "name": "UGC 11822",
                "image": "UGC 11822.png",
                "ra": 327.418700,
                "dec":40.663325,
                "type": "barred spiral",
                "redshift": 0.014739,
                "size": 1.170
            }
            
+ Response 204 (application/json)

## Galaxies Collection [/galaxies{?limit}]

### Retrieve All Galaxies [GET]

+ Parameters

    + limit (number, optional) - The maximum number of results to return.
        + Default: `10`

+ Response 200 (application/json)
    
        [
            {
                "pid": 1,
                "name": "UGC 11693",
                "image": "UGC 11693.png",
                "ra": 317.819183,
                "dec": 37.884811,
                "type": "spiral",
                "redshift": 0.093554,
                "size":1.227
            },
            {
                "pid": 2,
                "dec": 0,
                "name": "UGC 11822",
                "image": "UGC 11822.png",
                "ra": 327.418700,
                "dec":40.663325,
                "type": "barred spiral",
                "redshift": 0.014739,
                "size": 1.170
            }
        ]

+ Response 204 (application/json)