runtime: python
env: flex
entrypoint: gunicorn -b :$PORT idb:app
runtime_config:
  python_version: 3
automatic_scaling:
  max_idle_instances: 0
  max_num_instances: 1
env_variables:
  SQLALCHEMY_DATABASE_URI: >-
    postgresql+psycopg2://api:spacecowboys@/models?host=/cloudsql/spacecowboys-161302:us-central1:idb
beta_settings:
  cloud_sql_instances: spacecowboys-161302:us-central1:idb

